import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { SUPABASE_DIRECT_CONFIG } from '../config/supabaseConfig';

const STORAGE_KEY_URL = 'techworks_supabase_url';
const STORAGE_KEY_ANON = 'techworks_supabase_anon_key';

export function getStoredSupabaseConfig() {
  // 1. Vite client-side environment variables (if set)
  const envUrl = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_URL) || '';
  const envKey = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SUPABASE_ANON_KEY) || '';

  // 2. Direct hardcoded fallback (for 100% free Vercel deployment without touching Vercel Settings)
  const codeUrl = SUPABASE_DIRECT_CONFIG.url || '';
  const codeKey = SUPABASE_DIRECT_CONFIG.anonKey || '';

  // 3. Browser localStorage configuration via Admin UI
  const storedUrl = typeof window !== 'undefined' ? localStorage.getItem(STORAGE_KEY_URL) || '' : '';
  const storedKey = typeof window !== 'undefined' ? localStorage.getItem(STORAGE_KEY_ANON) || '' : '';

  const activeUrl = storedUrl || envUrl || codeUrl;
  const activeKey = storedKey || envKey || codeKey;

  return {
    url: activeUrl,
    anonKey: activeKey,
    isCustom: Boolean(storedUrl && storedKey),
    isConfigured: Boolean(activeUrl && activeKey),
  };
}

export function saveStoredSupabaseConfig(url: string, anonKey: string) {
  if (typeof window !== 'undefined') {
    if (url && anonKey) {
      localStorage.setItem(STORAGE_KEY_URL, url.trim());
      localStorage.setItem(STORAGE_KEY_ANON, anonKey.trim());
    } else {
      localStorage.removeItem(STORAGE_KEY_URL);
      localStorage.removeItem(STORAGE_KEY_ANON);
    }
  }
}

let cachedClient: SupabaseClient | null = null;
let lastUrl = '';
let lastKey = '';

export function getSupabaseClient(): SupabaseClient | null {
  const { url, anonKey } = getStoredSupabaseConfig();
  if (!url || !anonKey) return null;

  if (cachedClient && lastUrl === url && lastKey === anonKey) {
    return cachedClient;
  }

  try {
    cachedClient = createClient(url, anonKey, {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
      },
    });
    lastUrl = url;
    lastKey = anonKey;
    return cachedClient;
  } catch (err) {
    console.warn('Failed to initialize Supabase client:', err);
    return null;
  }
}

export const SUPABASE_SQL_SCHEMA = `-- 100% Free Supabase PostgreSQL setup for TechWorks:
-- 1. Create table public."TechWorks"
create table if not exists public."TechWorks" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "FULLNAME" text null,
  "EMAILADDRESS" text null,
  "PHONE NUMBER" text null,
  "PROJECT DESCRIPTION" text null,
  constraint TechWorks_pkey primary key (id)
) TABLESPACE pg_default;

-- 2. Enable Row Level Security (RLS)
alter table public."TechWorks" enable row level security;

-- 3. Policy to allow visitors to insert inquiries without logging in:
drop policy if exists "Allow public form submissions" on public."TechWorks";
create policy "Allow public form submissions"
on public."TechWorks" for insert
to anon, authenticated
with check (true);

-- 4. Policy to allow reading data:
drop policy if exists "Allow read access" on public."TechWorks";
create policy "Allow read access"
on public."TechWorks" for select
to anon, authenticated
using (true);

-- 5. Policy to allow deleting records (Admin):
drop policy if exists "Allow delete access" on public."TechWorks";
create policy "Allow delete access"
on public."TechWorks" for delete
to anon, authenticated
using (true);
`;
